### ISSUE TITLE
ReST GET expected result at file/{fid}

### ISSUE THREAD

**Issue by queenvictoria** [md-systems/file_entity#10]
Hi there. Please tell me if you're not answering questions here ;)

I've just installed the updated version with D8 HEAD (which is now installing well thank you).

I've:
- Enabled File Entity, HAL, Serialisation and ReST
- Configured permissive permissions for ReST
- Added a File entity to Article
- Added an Article with a file (a text file)
- Browsed (postman) to node/1 with application/hal+json (snippet below)
- Browsed to file/1 with  application/hal+json

Expected result
- Some sort of JSON structure for a file (so that I can replicate that with a POST)

Actual result
- 406 Not Acceptable

``` JSON
{
    "message": "Not Acceptable.",
    "supported_mime_types": [
        "text/html",
        "application/vnd.drupal-ajax",
        "application/vnd.drupal-dialog",
        "application/vnd.drupal-modal"
    ]
}
```

Is this expected?

node/{nid} snippet

``` JSON
{
    "_links": {
// ...
        "http://local.d8.example.com/rest/relation/node/article/field_file": [
            {
                "href": "http://local.d8.example.com/file/1"
            }
        ]
    },
// ...
    "_embedded": {
// ...
        "http://local.d8.example.com/rest/relation/node/article/field_file": [
            {
                "_links": {
                    "self": {
                        "href": "http://local.d8.example.com/file/1"
                    },
                    "type": {
                        "href": "http://local.d8.example.com/rest/type/file/document"
                    }
                },
                "uuid": [
                    {
                        "value": "e1438f29-f109-4e55-a660-967eb2bb5a0e"
                    }
                ],
                "display": "1",
                "description": ""
            }
        ]
    },
// ...
}
```

**Comment by arildm** [comment]
Not entirely sure, but you might have to add a few lines to the `rest.settings` config. If you have drush, the easiest might be to do `drush cedit rest.settings`, or otherwise you can do it through the configuration management UI. (I don't think there's a dedicated REST configuration UI.)

**Comment by Berdir** [comment]
Yes, you need to enable it in the rest settings. Thee is a contrib module that provides a UI, but it has not been updated in a while and is very likely broken at the moment: https://www.drupal.org/project/restui

**Comment by queenvictoria** [comment]
Perfect. Yes of course I forgot the crucial step! Thanks. Actually used Configuration Manager this time as I got an error using `drush cedit rest.settings` (though I've managed that before).

**Comment by Berdir** [comment]
Try updating drush, there was a core change related to saving configuration.
