### ISSUE TITLE
File Entity fields are not available in REST export

### ISSUE THREAD

**Issue by chrfritsch** [md-systems/file_entity#20]
1. Install File Entity
2. Add a custom field to the image entity
3. Add an image to node 1
4. REST GET on node/1

In the image field, the custom fields and the values for alt and title don't appear.

Maybe someone can give a hint, how to fix this, then i will try to create a patch.

**Comment by Berdir** [comment]
They aren't meant to appear. files are their own entity, you need to fetch them by doing a GET file/1. Just like you need to fetch term names or user names that belong to a node.

**Comment by chrfritsch** [comment]
Ok, i understand, but is this really the right way? Normally i want to make a minimum of request as possible. Especially for mobile apps

**Comment by Berdir** [comment]
right way isn't the question here :) It's REST. Each resource has it's own location/URL.

The question is whether the default REST services/patterns included in core are a good match for mobile apps/decoupled frontends. The answer is "Very likely not". As I said, it's the same for everything else. If you want to display a node with 3 tags and an author, you need 5 API requests. It's way more performant to built your own API that is design for your specific use case.

http://www.zensations.at/blog/headless-drupal-cake-lie is an interesting read on that topic, also the comments.

Either way, not much that file_entity could change about this. file entity (both the module and the entity type) just gets the default/generic core integration.
