### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by LKS90** [md-systems/file_entity#23]
I had a look at the test fails and started fixing them, but I currently have some problems with my development environment which make the tests take ages.

It's mosty just updating the test asserts (the exceptions are now unexpected :D), the xpath calls are all empty and one config (views.view.past_event_log) needs a dependency on the víews module.

**Comment by arildm** [comment]
Now the only remaining fail is this:

```
// @todo Next line causes an exception, core issue https://www.drupal.org/node/2462283
$this->drupalLogin($this->userAdmin);
```
