### ISSUE TITLE
Fix batch deletion of files.

### ISSUE THREAD

**Issue by LKS90** [md-systems/file_entity#25]
Deleting more than one file on admin/content/files by checking the box, selecting 'Delete file' and hitting 'Apply' is broken. No idea why yet.

**Comment by Berdir** [comment]
A few views criticals happened recently that are related to this. For example https://www.drupal.org/node/2486433. This might be causing the problem.

There are also related test fails about views render caching, https://www.drupal.org/node/2473873 is causing those.

**Comment by arildm** [comment]
I identified https://www.drupal.org/node/2484037 as the cause. "Quick-fixed" in 283aa2eb37e177fb70c4fecd3230c56226918b4a. AFAIK the file entity is translateable, so the actions should really be made properly translation-aware?

**Comment by Berdir** [comment]
I see. File entities currently aren't translatable, but maybe we'll add that in the future, so yes, it sounds like it should be implemented like nodes.
