### ISSUE TITLE
Add EntityInterface to FileEntity

### ISSUE THREAD

**Issue by LKS90** [md-systems/file_entity#26]
There is an exception about FileEntityNormalizer::getEntityUri($entity) not matching the parent class: ContentEntityNormalizer::getEntityUri(EntityInterface $entity)

Adding EntityInterface to the FileEntityNormalizer method isn't enough though, since FileEntity doesn't implement the EntityInterface yet.

**Comment by arildm** [comment]
Hm, yes, I just added the EntityInterface typehint to the method in fe3ebb8, making the test pass. FileEntity implements that interface but not directly.
FileEntity ⇾ File ⇾ FileInterface ⇾ ContentEntityInterface ⇾ FieldableEntityInterface ⇾ EntityInterface

**Comment by LKS90** [comment]
Then you should get an exception about FileEntity not implementing the EntityInterface in the tests.

**Comment by LKS90** [comment]
No errors about that on the travis-ci build, nevermind then:

https://travis-ci.org/md-systems/file_entity/jobs/67208511

**Comment by Berdir** [comment]
The fix looks fine. FileEntity can not not implement that interface, it extends from a class that does. It's more likely that the parent method there was changed and that broke it. That also means that the related core patches for bringing this into core need to be updated if they haven't been already.
