### ISSUE TITLE
Fatal error when replacing a file

### ISSUE THREAD

**Issue by mirodietiker** [md-systems/file_entity#57]
When updating a file, we have a fatal error:

Drupal\Core\Entity\EntityStorageException: 'thumbnail' not found in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 757 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
Drupal\Core\Entity\Query\Sql\Tables->addField('thumbnail.fid', 'INNER', NULL)
Drupal\Core\Entity\Query\Sql\Condition->compile(Object)
Drupal\Core\Entity\Query\Sql\Query->compile()
Drupal\Core\Entity\Query\Sql\Query->execute()
Drupal\file_entity\Entity\FileEntity->updateImageFieldDimensions()
Drupal\file_entity\Entity\FileEntity->postSave(Object, 1)
Drupal\Core\Entity\EntityStorageBase->doPostSave(Object, 1)
Drupal\Core\Entity\ContentEntityStorageBase->doPostSave(Object, 1)
Drupal\Core\Entity\EntityStorageBase->save(Object)
Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object)
Drupal\Core\Entity\Entity->save()

**Comment by tassilogroeper** [comment]
Actually, when reproducing the steps id get this error:

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "entity:file:undefined" plugin does not exist. in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 57 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

Drupal\Core\Plugin\DefaultPluginManager->getDefinition('entity:file:undefined')
Drupal\Core\TypedData\TypedDataManager->getCanonicalRepresentation(Object)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode(Object, NULL, 1)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate(Object, NULL, NULL)
Drupal\Core\TypedData\Validation\RecursiveValidator->validate(Object)
Drupal\Core\TypedData\TypedData->validate()
Drupal\Core\Entity\ContentEntityBase->validate()
Drupal\Core\Entity\ContentEntityForm->validateForm(Array, Object)
Drupal\file_entity\Form\FileEditForm->validateForm(Array, Object)
call_user_func_array(Array, Array)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'file_undefined_edit_form')
Drupal\Core\Form\FormValidator->validateForm('file_undefined_edit_form', Array, Object)
Drupal\Core\Form\FormBuilder->processForm('file_undefined_edit_form', Array, Object)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
call_user_func_array(Object, Array)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1)
Stack\StackedHttpKernel->handle(Object, 1, 1)
Drupal\Core\DrupalKernel->handle(Object)
```

Steps to reproduce:
- add a file with the backend button
- save that file
- go back to that file and try to replace it with another file, hit save

**Comment by Berdir** [comment]
Those two things have nothing in common. Please open separate, new issues in the drupal-media/file_entity project. The first is part of some new code that I recently ported, sounds like it is looking for a thumbnail field that it expects to exist but doesn't? Nut sure what the second is, but apparently the entity has the bundle/type undefined and that is not explicitly defined.

**Comment by slashrsm** [comment]
Done in https://github.com/drupal-media/file_entity/pull/4
